language: node_js
node_js:
  - 6

branches:
  only:
    - master
    - dev

install:
  npm install -g mocha
  npm install -g eslint

script:
  npm run build && npm test

sudo: false

cache:
  directories:
    - node_modules

notifications:
    email: false
